//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public System.Guid OrderLineID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
